"""
    Cisco SD-WAN vManage API

    The vManage API exposes the functionality of operations maintaining devices and the overlay network  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: vmanage@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.real_time_monitoring_ntp_api import RealTimeMonitoringNTPApi  # noqa: E501


class TestRealTimeMonitoringNTPApi(unittest.TestCase):
    """RealTimeMonitoringNTPApi unit test stubs"""

    def setUp(self):
        self.api = RealTimeMonitoringNTPApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_associations_list(self):
        """Test case for create_associations_list

        """
        pass

    def test_create_ntp_status_list(self):
        """Test case for create_ntp_status_list

        """
        pass

    def test_create_peer_list(self):
        """Test case for create_peer_list

        """
        pass

    def test_create_te_list(self):
        """Test case for create_te_list

        """
        pass

    def test_create_utd_list(self):
        """Test case for create_utd_list

        """
        pass

    def test_create_waas_list(self):
        """Test case for create_waas_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
