"""
    Cisco SD-WAN vManage API

    The vManage API exposes the functionality of operations maintaining devices and the overlay network  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: vmanage@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.real_time_monitoring_transport_api import RealTimeMonitoringTransportApi  # noqa: E501


class TestRealTimeMonitoringTransportApi(unittest.TestCase):
    """RealTimeMonitoringTransportApi unit test stubs"""

    def setUp(self):
        self.api = RealTimeMonitoringTransportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_transport_connection_list(self):
        """Test case for create_transport_connection_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
