"""
    Cisco SD-WAN vManage API

    The vManage API exposes the functionality of operations maintaining devices and the overlay network  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: vmanage@cisco.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_o365_preferred_path_from_v_analytics_request_value import GetO365PreferredPathFromVAnalyticsRequestValue


class TestGetO365PreferredPathFromVAnalyticsRequestValue(unittest.TestCase):
    """GetO365PreferredPathFromVAnalyticsRequestValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetO365PreferredPathFromVAnalyticsRequestValue(self):
        """Test GetO365PreferredPathFromVAnalyticsRequestValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetO365PreferredPathFromVAnalyticsRequestValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
