"""
    Cisco SD-WAN vManage API

    The vManage API exposes the functionality of operations maintaining devices and the overlay network  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: vmanage@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.configuration_circuits_api import ConfigurationCircuitsApi  # noqa: E501


class TestConfigurationCircuitsApi(unittest.TestCase):
    """ConfigurationCircuitsApi unit test stubs"""

    def setUp(self):
        self.api = ConfigurationCircuitsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_circuit(self):
        """Test case for create_circuit

        """
        pass

    def test_delete_circuit(self):
        """Test case for delete_circuit

        """
        pass

    def test_edit_circuit(self):
        """Test case for edit_circuit

        """
        pass

    def test_get_circuits(self):
        """Test case for get_circuits

        """
        pass


if __name__ == '__main__':
    unittest.main()
