"""
    Cisco SD-WAN vManage API

    The vManage API exposes the functionality of operations maintaining devices and the overlay network  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: vmanage@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.monitoring_bridge_api import MonitoringBridgeApi  # noqa: E501


class TestMonitoringBridgeApi(unittest.TestCase):
    """MonitoringBridgeApi unit test stubs"""

    def setUp(self):
        self.api = MonitoringBridgeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_aggregation_data_by_query5(self):
        """Test case for get_aggregation_data_by_query5

        """
        pass

    def test_get_aggregation_data_by_query6(self):
        """Test case for get_aggregation_data_by_query6

        """
        pass

    def test_get_count7(self):
        """Test case for get_count7

        """
        pass

    def test_get_count8(self):
        """Test case for get_count8

        """
        pass

    def test_get_count_post7(self):
        """Test case for get_count_post7

        """
        pass

    def test_get_count_post8(self):
        """Test case for get_count_post8

        """
        pass

    def test_get_post_aggregation_app_data_by_query5(self):
        """Test case for get_post_aggregation_app_data_by_query5

        """
        pass

    def test_get_post_aggregation_app_data_by_query6(self):
        """Test case for get_post_aggregation_app_data_by_query6

        """
        pass

    def test_get_post_aggregation_data_by_query5(self):
        """Test case for get_post_aggregation_data_by_query5

        """
        pass

    def test_get_post_aggregation_data_by_query6(self):
        """Test case for get_post_aggregation_data_by_query6

        """
        pass

    def test_get_post_stat_bulk_raw_data5(self):
        """Test case for get_post_stat_bulk_raw_data5

        """
        pass

    def test_get_post_stat_bulk_raw_data6(self):
        """Test case for get_post_stat_bulk_raw_data6

        """
        pass

    def test_get_stat_bulk_raw_data5(self):
        """Test case for get_stat_bulk_raw_data5

        """
        pass

    def test_get_stat_bulk_raw_data6(self):
        """Test case for get_stat_bulk_raw_data6

        """
        pass

    def test_get_stat_data_fields7(self):
        """Test case for get_stat_data_fields7

        """
        pass

    def test_get_stat_data_fields8(self):
        """Test case for get_stat_data_fields8

        """
        pass

    def test_get_stat_data_raw_data5(self):
        """Test case for get_stat_data_raw_data5

        """
        pass

    def test_get_stat_data_raw_data6(self):
        """Test case for get_stat_data_raw_data6

        """
        pass

    def test_get_stat_data_raw_data_as_csv5(self):
        """Test case for get_stat_data_raw_data_as_csv5

        """
        pass

    def test_get_stat_data_raw_data_as_csv6(self):
        """Test case for get_stat_data_raw_data_as_csv6

        """
        pass

    def test_get_stat_query_fields7(self):
        """Test case for get_stat_query_fields7

        """
        pass

    def test_get_stat_query_fields8(self):
        """Test case for get_stat_query_fields8

        """
        pass

    def test_get_stats_raw_data5(self):
        """Test case for get_stats_raw_data5

        """
        pass

    def test_get_stats_raw_data6(self):
        """Test case for get_stats_raw_data6

        """
        pass


if __name__ == '__main__':
    unittest.main()
