"""
    Cisco SD-WAN vManage API

    The vManage API exposes the functionality of operations maintaining devices and the overlay network  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: vmanage@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.real_time_monitoring_wlan_api import RealTimeMonitoringWLANApi  # noqa: E501


class TestRealTimeMonitoringWLANApi(unittest.TestCase):
    """RealTimeMonitoringWLANApi unit test stubs"""

    def setUp(self):
        self.api = RealTimeMonitoringWLANApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_wlan_clients(self):
        """Test case for get_wlan_clients

        """
        pass

    def test_get_wlan_interfaces(self):
        """Test case for get_wlan_interfaces

        """
        pass

    def test_get_wlan_radios(self):
        """Test case for get_wlan_radios

        """
        pass

    def test_get_wlan_radius(self):
        """Test case for get_wlan_radius

        """
        pass


if __name__ == '__main__':
    unittest.main()
