"""
    Cisco SD-WAN vManage API

    The vManage API exposes the functionality of operations maintaining devices and the overlay network  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: vmanage@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.real_time_monitoring_cfm_api import RealTimeMonitoringCFMApi  # noqa: E501


class TestRealTimeMonitoringCFMApi(unittest.TestCase):
    """RealTimeMonitoringCFMApi unit test stubs"""

    def setUp(self):
        self.api = RealTimeMonitoringCFMApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_mp_database(self):
        """Test case for get_mp_database

        """
        pass

    def test_get_mp_local_mep(self):
        """Test case for get_mp_local_mep

        """
        pass

    def test_get_mp_local_mip(self):
        """Test case for get_mp_local_mip

        """
        pass

    def test_get_mp_remote_mep(self):
        """Test case for get_mp_remote_mep

        """
        pass


if __name__ == '__main__':
    unittest.main()
