"""
    Cisco SD-WAN vManage API

    The vManage API exposes the functionality of operations maintaining devices and the overlay network  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: vmanage@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.monitoring_flowlog_api import MonitoringFlowlogApi  # noqa: E501


class TestMonitoringFlowlogApi(unittest.TestCase):
    """MonitoringFlowlogApi unit test stubs"""

    def setUp(self):
        self.api = MonitoringFlowlogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_aggregation_data_by_query26(self):
        """Test case for get_aggregation_data_by_query26

        """
        pass

    def test_get_count28(self):
        """Test case for get_count28

        """
        pass

    def test_get_count_post28(self):
        """Test case for get_count_post28

        """
        pass

    def test_get_post_aggregation_app_data_by_query25(self):
        """Test case for get_post_aggregation_app_data_by_query25

        """
        pass

    def test_get_post_aggregation_data_by_query26(self):
        """Test case for get_post_aggregation_data_by_query26

        """
        pass

    def test_get_post_stat_bulk_raw_data26(self):
        """Test case for get_post_stat_bulk_raw_data26

        """
        pass

    def test_get_stat_bulk_raw_data26(self):
        """Test case for get_stat_bulk_raw_data26

        """
        pass

    def test_get_stat_data_fields28(self):
        """Test case for get_stat_data_fields28

        """
        pass

    def test_get_stat_data_raw_data25(self):
        """Test case for get_stat_data_raw_data25

        """
        pass

    def test_get_stat_data_raw_data_as_csv26(self):
        """Test case for get_stat_data_raw_data_as_csv26

        """
        pass

    def test_get_stat_query_fields28(self):
        """Test case for get_stat_query_fields28

        """
        pass

    def test_get_stats_raw_data26(self):
        """Test case for get_stats_raw_data26

        """
        pass


if __name__ == '__main__':
    unittest.main()
