"""
    Cisco SD-WAN vManage API

    The vManage API exposes the functionality of operations maintaining devices and the overlay network  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: vmanage@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.resource_pool_api import ResourcePoolApi  # noqa: E501


class TestResourcePoolApi(unittest.TestCase):
    """ResourcePoolApi unit test stubs"""

    def setUp(self):
        self.api = ResourcePoolApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_resources(self):
        """Test case for create_resources

        """
        pass

    def test_delete_resources(self):
        """Test case for delete_resources

        """
        pass

    def test_get_resources(self):
        """Test case for get_resources

        """
        pass


if __name__ == '__main__':
    unittest.main()
