"""
    Cisco SD-WAN vManage API

    The vManage API exposes the functionality of operations maintaining devices and the overlay network  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: vmanage@cisco.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.software_upload_file_data import SoftwareUploadFileData
globals()['SoftwareUploadFileData'] = SoftwareUploadFileData
from openapi_client.model.tag_restful_resource import TagRestfulResource


class TestTagRestfulResource(unittest.TestCase):
    """TagRestfulResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagRestfulResource(self):
        """Test TagRestfulResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TagRestfulResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
