"""
    Cisco SD-WAN vManage API

    The vManage API exposes the functionality of operations maintaining devices and the overlay network  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: vmanage@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.real_time_monitoring_crash_log_api import RealTimeMonitoringCrashLogApi  # noqa: E501


class TestRealTimeMonitoringCrashLogApi(unittest.TestCase):
    """RealTimeMonitoringCrashLogApi unit test stubs"""

    def setUp(self):
        self.api = RealTimeMonitoringCrashLogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_device_crash_logs(self):
        """Test case for get_all_device_crash_logs

        """
        pass

    def test_get_device_crash_information(self):
        """Test case for get_device_crash_information

        """
        pass

    def test_get_device_crash_logs(self):
        """Test case for get_device_crash_logs

        """
        pass

    def test_get_device_crash_logs_synced(self):
        """Test case for get_device_crash_logs_synced

        """
        pass


if __name__ == '__main__':
    unittest.main()
